# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [245]:
import numpy as np

2. Create a null vector of size 10 

In [197]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [198]:
q3 = np.arange(10,50)
q3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [199]:
q3.shape

(40,)

5. Print the type of the previous array in question 3

In [200]:
q3.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [201]:
print('Numpy VERSION:', np.version.version)
print(np.show_config())

Numpy VERSION: 1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/saoud/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/saoud/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/saoud/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/saoud/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/saoud/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/saoud/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/saoud/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/saoud/anaconda3/include']
None


7. Print the dimension of the array in question 3


In [202]:
q3.ndim

1

8. Create a boolean array with all the True values

In [203]:
#method 1
true_arr1 = np.ones(10, dtype=bool)
print(true_arr1)
print(f'true_arr1 dtype is {true_arr1.dtype}')
# method 2
true_arr2 = np.arange(1,11).astype(bool)
print(true_arr2)
print(f'true_arr2 dtype is {true_arr2.dtype}')

[ True  True  True  True  True  True  True  True  True  True]
true_arr1 dtype is bool
[ True  True  True  True  True  True  True  True  True  True]
true_arr2 dtype is bool


9. Create a two dimensional array




In [204]:
#method 1
arr_2d = np.array([[1,2,3],[3,4,5]])
print(f'array \n{arr_2d} is {arr_2d.ndim}D')
#method 2
array_2d = np.arange(5, 11).reshape(2,3)
print(f'array \n{array_2d} is {array_2d.ndim}D')

array 
[[1 2 3]
 [3 4 5]] is 2D
array 
[[ 5  6  7]
 [ 8  9 10]] is 2D


10. Create a three dimensional array



In [205]:
#method 1
arr_3d = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(f'array \n{arr_3d} is {arr_3d.ndim}D')
#method 2
array_3d = np.arange(9, 18).reshape(1,3,3)
print(f'array \n{array_3d} is {array_3d.ndim}D')

array 
[[[1 2 3]
  [3 4 5]
  [6 7 8]]] is 3D
array 
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]] is 3D


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [206]:
arr = np.arange(1,11)
print(f'array: {arr}')
reverse_arr = arr[::-1]
print(f'reverse array: {reverse_arr}')

array: [ 1  2  3  4  5  6  7  8  9 10]
reverse array: [10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [207]:
null_vector = np.zeros(10, dtype='int32')
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [208]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [209]:
arr = np.array([1, 2, 3, 4, 5]).astype('float')
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [210]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [211]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.array((arr1==arr2))

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [212]:
arr = np.arange(0,9)
odd_arr = arr[arr%2==1]
print(odd_arr)

[1 3 5 7]


18. Replace all odd numbers to -1 from previous array

In [213]:
arr[odd_arr] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [214]:
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [215]:
def border_ones_inside_zeros(size, rows, cols):
    arr = np.ones(size, dtype='int').reshape(rows,cols)
    arr[1:arr.shape[0]-1, 1:arr.shape[1]-1] = 0
    return f'{arr}\n'
print(border_ones_inside_zeros(9,3,3))
print(border_ones_inside_zeros(15,3,5))
print(border_ones_inside_zeros(20,5,4))
print(border_ones_inside_zeros(40,8,5))

[[1 1 1]
 [1 0 1]
 [1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]



Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [216]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [217]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [218]:
arr = np.arange(0,9).reshape(3,3)
print(arr,'\n')
first_arr = arr[0]
print(f'First {first_arr} is {first_arr.ndim}-D array')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

First [0 1 2] is 1-D array


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
arr = np.arange(0,9).reshape(3,3)
print(arr,'\n')
second_arr = arr[1]
print(f'Second {second_arr} is {second_arr.ndim}-D array')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Second [3 4 5] is 1-D array


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
arr = np.arange(0,9).reshape(3,3)
print(arr,'\n')
third_col = arr[:2,2]
print(third_col)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [256]:
random_array = np.random.rand(10,10)
print(f'Random Array: {random_array}\n')
print(f'Maximum Value = {random_array.max()}\nMinimum Value = {random_array.min()}')

Random Array: [[0.00268043 0.02870038 0.94805472 0.02687777 0.08336443 0.75848997
  0.60927814 0.49823642 0.48864144 0.18855389]
 [0.69465636 0.17629848 0.9677938  0.34656835 0.98141091 0.41580769
  0.42554317 0.44144041 0.65512729 0.13398329]
 [0.49813787 0.67777822 0.81165248 0.22669092 0.88313127 0.91258352
  0.14751285 0.06319976 0.66296295 0.00801898]
 [0.76845798 0.22599035 0.53236691 0.16158578 0.73764969 0.04376149
  0.18628627 0.87499102 0.34938005 0.08145628]
 [0.01071398 0.72371106 0.08302053 0.06166773 0.93953001 0.05993706
  0.20659828 0.80371793 0.39796704 0.62044643]
 [0.53266168 0.42564807 0.9927605  0.24958075 0.96570393 0.09764019
  0.65154489 0.81186013 0.77693703 0.26376976]
 [0.44238941 0.8222608  0.49914863 0.25007047 0.64189761 0.68381995
  0.939792   0.57475794 0.89759473 0.91995953]
 [0.03681735 0.09614556 0.12255368 0.99480377 0.9510461  0.42286776
  0.67470198 0.83096535 0.55985716 0.12732765]
 [0.99498243 0.40136837 0.34966288 0.36604393 0.27144579 0.7436685

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [252]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f'Common items between array a and b is {np.intersect1d(a,b)}')

Common items between array a and b is [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [253]:
print(np.where((a==b) == True)[0])

[1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [254]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will']

array([[ 0.26823159, -0.45741031,  1.60385855, -0.52579026],
       [ 0.45090242, -2.02055042, -0.82103753,  0.09114285],
       [ 0.69478699,  0.75314787, -1.75611782, -1.20318688],
       [-0.8600206 ,  0.41835639, -1.82349921,  1.20442685],
       [-1.2825801 ,  0.96092252,  2.26948937, -1.4058046 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [255]:
data[(names != 'Will') & (names != 'Joe')]

array([[ 0.26823159, -0.45741031,  1.60385855, -0.52579026],
       [ 0.69478699,  0.75314787, -1.75611782, -1.20318688]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [155]:
arr2d = np.arange(1,16).reshape(5,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [243]:
arr3d = np.arange(1,17).reshape(2,2,4)
print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [244]:
print(arr3d.transpose())
print('------------')
print(np.swapaxes(arr3d,0,2))

[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]
------------
[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [273]:
arr = np.random.rand(10)
print('Random Array:', arr,'\n')

sqrt_arr = arr**0.5
print('SQRT of Above Array:', sqrt_arr,'\n')
sqrt_arr[sqrt_arr<0.5] = 0
print('Replaced Array:', sqrt_arr)

Random Array: [0.97042925 0.49527267 0.62986553 0.04373147 0.03620156 0.18313778
 0.58447961 0.71296112 0.80310912 0.74519494] 

SQRT of Above Array: [0.98510368 0.70375611 0.79364068 0.2091207  0.19026707 0.427946
 0.76451266 0.84437025 0.89616356 0.86324674] 

Replaced Array: [0.98510368 0.70375611 0.79364068 0.         0.         0.
 0.76451266 0.84437025 0.89616356 0.86324674]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [250]:
arr1, arr2 = np.random.randn(12),np.random.randn(12)
print(arr1)
print("".join(['-' for _ in range(73)]))
print(arr2)
arr3 = np.maximum(arr1, arr2)
print("".join(['-' for _ in range(73)]))
print(arr3)

[ 1.88395852 -0.76402463  0.57582637 -0.98633257 -2.03025763  0.29615845
 -0.58248559 -2.35440265  1.03088083  0.89246867  1.36424779  0.52703061]
-------------------------------------------------------------------------
[-1.16819275  0.3503786  -2.37478317 -1.11743597 -0.77548192  0.46393998
 -0.72684881  0.20477306 -1.78326684  0.00707582  0.30185427  0.38249758]
-------------------------------------------------------------------------
[ 1.88395852  0.3503786   0.57582637 -0.98633257 -0.77548192  0.46393998
 -0.58248559  0.20477306  1.03088083  0.89246867  1.36424779  0.52703061]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(np.sort(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [114]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [161]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([10,10,10])
print(sampleArray)
newArray = np.delete(sampleArray,1,1) #delete col 2
newArray = np.insert(newArray,1,newColumn,1) #insert newColumn inplace of deleted col
newArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [167]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print()
print(y)
np.dot(x,y)

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [246]:
arr = np.random.randint(4, size=(20)).reshape(4,5)
print(arr) # 4 by 5 matrix of 20 randdom int values
print()
print(np.cumsum(arr)) # cumulative sum


[[3 3 3 1 0]
 [3 0 2 2 3]
 [3 2 0 0 3]
 [1 2 0 3 0]]

[ 3  6  9 10 10 13 13 15 17 20 23 25 25 25 28 29 31 31 34 34]
