# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
arr_v = np.vstack((arr1,arr2))
arr_v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr_h = np.hstack((arr1,arr2))
arr_h

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
#method 1
a.ravel()


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#method 2
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#method 3
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
arr3d = np.arange(15).reshape(3,5,1)
arr3d

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [8]:
arr = np.arange(15)
np.resize(arr, (5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [9]:
arr = np.arange(1,26).reshape(5,5)**2
arr

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

## Question:8

### Create 5x6 an array and find the mean?

In [10]:
arr_m = np.arange(30,0,-1).reshape(5,6)
np.mean(arr_m)

15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [11]:
np.std(arr_m)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [12]:
np.median(arr_m)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [13]:
print(arr_m)
np.transpose(arr_m)

[[30 29 28 27 26 25]
 [24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


array([[30, 24, 18, 12,  6],
       [29, 23, 17, 11,  5],
       [28, 22, 16, 10,  4],
       [27, 21, 15,  9,  3],
       [26, 20, 14,  8,  2],
       [25, 19, 13,  7,  1]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [14]:
arr_d = np.arange(1,17).reshape(4,4)*10
print(arr_d)
print(f'Diagonal Sum: {arr_d.trace()}')
print(f'Acutal Sum: {np.sum(arr_d)}')

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
Diagonal Sum: 340
Acutal Sum: 1360


## Question:13

### Find the determinant of the previous array in Q12?

In [15]:
print(f'Determinant: {np.linalg.det(arr_d)}')

Determinant: 1.7524848417525418e-26


## Question:14

### Find the 5th and 95th percentile of an array?

In [16]:
print(arr_d)
print("5th percentile: ",np.percentile(arr_d, 5))
print("95th percentile: ",np.percentile(arr_d, 95))

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
5th percentile:  17.5
95th percentile:  152.5


## Question:15

### How to find if a given array has any null values?

In [17]:
arr1 = np.array([1,2,3,4,np.NaN,6])
print(np.isnan(arr1).any())
arr2 = np.array([1,2,3,4,6])
print(np.isnan(arr2).any())

True
False
